import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import QueryProvider from "@/components/QueryProvider/QueryProvider";
import ToastProvider from "@/components/ToastProvider/ToastProvider";
import CoopErrorSuppressor from "@/components/CoopErrorSuppressor/CoopErrorSuppressor";
import "izitoast/dist/css/iziToast.min.css";

const roboto = Roboto({
  weight: ["400", "500"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal?: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <CoopErrorSuppressor />
        <ToastProvider />
        <QueryProvider>
          <Header />
          <main>{children}</main>
        </QueryProvider>
        {/* Parallel route slot for intercepted modals */}
        {modal}
      </body>
    </html>
  );
}
